# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _LLE
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


swig_compute_neighbors_1 = _LLE.swig_compute_neighbors_1
swig_compute_neighbors_2 = _LLE.swig_compute_neighbors_2
swig_compute_LLE_weights_1 = _LLE.swig_compute_LLE_weights_1
swig_compute_LLE_weights_2 = _LLE.swig_compute_LLE_weights_2
swig_compute_LLE_weights_3 = _LLE.swig_compute_LLE_weights_3
swig_compute_LLE_weights_4 = _LLE.swig_compute_LLE_weights_4
swig_compute_LLE_dim_1 = _LLE.swig_compute_LLE_dim_1
swig_compute_LLE_dim_2 = _LLE.swig_compute_LLE_dim_2
swig_LLE_1 = _LLE.swig_LLE_1
swig_LLE_2 = _LLE.swig_LLE_2
swig_HLLE_1 = _LLE.swig_HLLE_1
swig_HLLE_2 = _LLE.swig_HLLE_2
swig_MLLE_1 = _LLE.swig_MLLE_1
swig_MLLE_2 = _LLE.swig_MLLE_2
swig_RLLE1_1 = _LLE.swig_RLLE1_1
swig_RLLE1_2 = _LLE.swig_RLLE1_2
swig_RLLE2_1 = _LLE.swig_RLLE2_1
swig_RLLE2_2 = _LLE.swig_RLLE2_2
swig_compute_RLLE_scores_1 = _LLE.swig_compute_RLLE_scores_1
swig_compute_RLLE_scores_2 = _LLE.swig_compute_RLLE_scores_2
swig_compute_mean_dist = _LLE.swig_compute_mean_dist
swig_project_onto_LLE_1 = _LLE.swig_project_onto_LLE_1
swig_project_onto_LLE_2 = _LLE.swig_project_onto_LLE_2
swig_project_onto_LLE_3 = _LLE.swig_project_onto_LLE_3
swig_compute_sigma_1 = _LLE.swig_compute_sigma_1
swig_compute_sigma_2 = _LLE.swig_compute_sigma_2


